name: Trigger GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    uses: unbounded-tech/workflow-simple-release/.github/workflows/workflow.yaml@main
    with:
      tag: ${{ github.ref_name }}
      name: ${{ github.ref_name }}
